// Generated by build.rs — scans src/features/*/tests/world.rs at build
// time and emits #[test] fn stubs that call each slice's run().
// See build.rs for generation logic and slice discovery.
include!(concat!(env!("OUT_DIR"), "/feature_slices.rs"));
